### ISSUE TITLE
Publish to NPM package

### ISSUE THREAD

**Issue by nichlaes** [INTO-CPS-Association/DTaaS#1001]
### Describe the feature

As a developer, I want the CD to deploy to both Github NPM and NPM.JS

### Describe the solution you'd like

A github workflow template file for publishing to a given npm registry.

### Additional context

The code should be tested by forking the main branch and then testing the CD flow to a personal NPM registry.

### Success Criterion

The issue is resolved when:

Checklist:

- [ ] Npm package is deployed to Node js registry through github actions

**Comment by prasadtalasila** [comment]
This is related to #969

**Comment by nichlaes** [comment]
@prasadtalasila I thought this was the one I should make an issue for?

**Comment by prasadtalasila** [comment]
Yes. But I forgot about an already open issue that describes the same feature (issue #969). That is why this issue has been closed.
