### ISSUE TITLE
[FEATURE] Add Create tab into Digital Twins page preview

### ISSUE THREAD

**Issue by VanessaScherma** [INTO-CPS-Association/DTaaS#1002]
### Describe the feature

As a **user**, I want to **configure the files of a new digital twin via the Create tab interface**
so that **I can add a new digital twin folder to my GitLab profile**

### Describe the problems your feature request solves

At the moment, the Digital Twins page preview only offers the possibility of reconfiguring existing digital twins. The possibility of creating a new digital twin is to be added.

### Describe the solution you'd like

The Editor component is intended to be reused to enable the configuration of a new digital twin.

When opening the Create tab, the Sidebar will maintain the same sections (Description, Configuration, Lifecycle), displaying the following files with empty content:
- `README.md`
- `description.md`
- `.gitlab-ci.yml`

The user can modify the content of the files and add more files. It is not possible to remove the `.gitlab-ci.yml` file, as it is mandatory for the execution of the digital twin pipeline.

### Describe alternatives you've considered

None.

### Additional context

None.

### Success Criterion

A new folder, having the name of the new digital twin, is created within the `digitaltwins` folder of the user's GitLab profile. The folder contains the configured files.

Checklist:

- [ ] Properly functioning feature
- [ ] 100% test coverage
- [ ] No codeclimate issues

**Comment by prasadtalasila** [comment]
completed in PR #1005
