### ISSUE TITLE
git push doesnt work on vscode terminal

### ISSUE THREAD

**Issue by aryanbhosale** [INTO-CPS-Association/DTaaS#1003]
After staging/committing I try to git push my changes to my repo, but that doesnt work
The first time it asks to open an authorization link, which when opened says "ERROR", subsequently it doesnt ask for opening the auth url and just runs forever

### To Reproduce

1. git add <your changes>
1. git commit -m "message"
1. git push

### Expected behavior

Should successfully push the updated code 

### Workaround

1. 
```
(type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
	&& sudo mkdir -p -m 755 /etc/apt/keyrings \
	&& wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
	&& sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
	&& sudo apt update \
	&& sudo apt install gh -y
```

2.  `sudo apt update`
`sudo apt install gh`

3. in the terminal: `gh auth login`
4. After the SSH/HTTPS option, choose the personal access token option when prompted and paste your personal access token in the terminal

It works after this

**Comment by prasadtalasila** [comment]
@aryanbhosale this authorization flow is very specific to GitHub. Even GitHub supports SSH key / HTTP token. There no plans to add this extra feature at the moment. But thanks for the suggestion.
