### ISSUE TITLE
[BUG] libms internal load build context fails when building docker/compose.dev.yml

### ISSUE THREAD

**Issue by atomicgamedeveloper** [INTO-CPS-Association/DTaaS#1029]
### Describe the bug

Running `docker compose -f compose.dev.yml build` in `/docker` fails to build with the following error regarding loading the build context for libms.

```
[+] Building 28.1s (11/26)                                                                                                              docker:desktop-linux
[...]
 => [libms build 1/6] FROM docker.io/library/node:20.10.0-slim@sha256:5c714c3e90f66a2cbfa266b90a4d7adcd63453cd730aa2d13cba84b260bea2e6                  0.0s 
 => ERROR [libms internal] load build context                                                                                                          26.0s 
 => => transferring context: 537.36MB                                                                                                                  25.9s 
[...]
 => CANCELED [client build 4/6] RUN yarn install --immutable --immutable-cache --check-cache                                                           16.8s
------
 > [libms internal] load build context:
------
failed to solve: archive/tar: unknown file mode ?rwxr-xr-x
```

### To Reproduce

1. Go to './docker'
1. Run `docker compose -f compose.dev.yml build`
1. See error

### Expected behavior

The compose.dev.yml to be built succesfully.

### Screenshots

![image](https://github.com/user-attachments/assets/ef500981-f9e1-437f-be7c-11a663b5c357)

### Application Environment

Please provide the following information:

- OS: Windows 11
- Browser Firefox
- DTaaS Release 0.5.0
- Docker version 4.31.1 (153621)

### Additional context

Nothing to add.

**Comment by prasadtalasila** [comment]
@atomicgamedeveloper Both @nichlaes and I can't replicate this error. Can you please check your docker installation again? You can also try running in a fresh Ubuntu VM and see the result.

**Comment by atomicgamedeveloper** [comment]
> @atomicgamedeveloper Both @nichlaes and I can't replicate this error. Can you please check your docker installation again? You can also try running in a fresh Ubuntu VM and see the result.

Rebuilding from feature/distributed-demo's HEAD worked. Not sure why it happened, but maybe some interaction with my local changes in that folder.

**Comment by prasadtalasila** [comment]
No longer a problem
