### ISSUE TITLE
[BUG] preview/digitaltwins route works with maestro but not gitlab.com

### ISSUE THREAD

**Issue by atomicgamedeveloper** [INTO-CPS-Association/DTaaS#1031]
### Describe the bug

Going to https://localhost/preview/digitaltwins after spinning up `DTaaS\deploy\docker\compose.local.yml` prompts an error when it loads the user files. This works when using the maestro gitlab instance.

### To Reproduce

1. Configure `DTaaS\deploy\docker\.env.local` with your dtaas folder path and gitlab name
1. Similarly, configure `\DTaaS\deploy\config\client\env.local.js` with a gitlab.com `REACT_APP_CLIENT_ID` and `REACT_APP_AUTH_AUTHORITY`
1. Start the docker file with `docker compose -f compose.local.yml --env-file .env.local up -d` from the `deploy\docker` folder
1. Navigate to `preview/digitaltwins` route on website
1. See error

### Expected behavior

For the sample digital twins to show up.

### Screenshots
gitlab.com:
![image](https://github.com/user-attachments/assets/0e42aefa-efe5-47c2-ac60-0cac854a25f1)

maestro:
![image](https://github.com/user-attachments/assets/bea8a39f-ed54-4ab9-a1c5-f43809607efd)

### Application Environment

Please provide the following information:

- OS: Windows 11
- Browser: Firefox
- DTaaS Release: 0.5.0

### Additional context

None.

**Comment by prasadtalasila** [comment]
This is due to the CORS policy of gitlab.com. Nothing could be done about it.
