### ISSUE TITLE
[BUG] Workbench Execute tab fails to start the digital twin

### ISSUE THREAD

**Issue by aryanpingle** [INTO-CPS-Association/DTaaS#1045]
In the `Workbench > Digital Twins Preview > Execute` tab, pressing _Start_ on the `Hello World` digital twin throws this error:

```
Execution error for Hello World
```

![image](https://github.com/user-attachments/assets/f2553045-153d-4c08-8936-4905aa1f5e52)

The developer tools console shows these 3 errors:

![image](https://github.com/user-attachments/assets/a6dc527d-5d56-4973-9f78-3d24e7ebf5d1)

![image](https://github.com/user-attachments/assets/94b96d40-02ca-438e-a98d-366dac8412fd)

![image](https://github.com/user-attachments/assets/5d9ed247-ec65-4ec9-9c3b-ac67870efd37)

## Steps to reproduce

After creating a runner according to [this guide](https://github.com/INTO-CPS-Association/DTaaS/blob/feature/distributed-demo/docs/developer/client/GITLAB-RUNNER.md):

1. Bring up compose.dev.yml on localhost
1. Go to `Workbench > Digital Twins Preview > Execute`
1. Press start on any of the digital twins (in this example, `Hello World`)

**Comment by prasadtalasila** [comment]
Could not be replicated
