### ISSUE TITLE
[FEATURE] Add Library page preview

### ISSUE THREAD

**Issue by VanessaScherma** [INTO-CPS-Association/DTaaS#1080]
### Describe the feature
As a **user**, I want to **display library assets, both common and private**
so that **I can reuse pre-existing assets to create new digital twins**

### Describe the problems your feature request solves

At the moment, the creation functionality only supports creation from scratch. It is intended to add the possibility of displaying library assets, both common and private, so that they can be selected and used in the creation phase, possibly by reconfiguring them.

### Describe the solution you'd like

It is intended to create a _Library page preview_ and add its link to the workbench. In particular, this allows user to display assets, separating them by type (digital twins, models, tools, etc.) and privacy (common or private).

Each asset will have an ‘add to cart’ button. The cart, also visible on the page, stores the assets to be reused in the creation phase.

### Describe alternatives you've considered

None.

### Additional context

None.

### Success Criterion

When creating a digital twin using one or more assets, the digital_twins folder of the user's GitLab profile will include a new folder with the name of the newly created digital twin. In addition, this will include folders with the files of the reused assets, having the configuration files updated with the contents specified in the Create tab.

Checklist:

- [ ] Properly functioning feature
- [ ] Test coverage is improved
- [ ] No codeclimate issues

**Comment by prasadtalasila** [comment]
PR #1081 adds the feature
