### ISSUE TITLE
[BUG]Mistakes in READMEs of libms

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#1095]
### Describe the bug

There are two mistakes in the [README](https://github.com/INTO-CPS-Association/DTaaS/blob/feature/distributed-demo/servers/lib/README.md) of lib microservice. The mistakes are:

1. Config format should have been specified in yaml not ini format on [config section](https://github.com/INTO-CPS-Association/DTaaS/blob/feature/distributed-demo/servers/lib/README.md#gear-configure)
2. The default config format - libms.yaml.default - is mentioned but this is not available to users installing npm package. Please move this to DEVELOPER.md

**Comment by nichlaes** [comment]
@prasadtalasila The libms.yaml.default is only mentioned as an example for another config file. So I guess it's okay to have. Or do you want me to make another example in the readme?
