### ISSUE TITLE
Codecov upload error

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#15]
Codecov reports are not being uploaded correctly.

**Comment by Omarley7** [comment]
@prasadtalasila I assume this is the missing coverage on codeclimate?

**Comment by Omarley7** [comment]
@prasadtalasila The upload seems to be working fine. The issue was generation of the coverage report. We have it working on our [fork]((https://app.codecov.io/github/MAO-GUI-developers/DTaaS-Bachelor-new-GUI) atm (only unittest so far), so should start working after next PR.

**Comment by prasadtalasila** [comment]
@Omarley7 Let's keep this open until the PR is merged.

**Comment by prasadtalasila** [comment]
This issue has been solved in PR #20.

**Comment by prasadtalasila** [comment]
The playwright tests are still not uploaded correctly to codecov. This needs fixing.

**Comment by prasadtalasila** [comment]
issue #45 has more details on the playwright test upload to codecov. No need to have this issue open.
