### ISSUE TITLE
Web GUI Things to fix

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#18]
* Add unit tests and remove warning for react grid test
* Forward unknown routes to backend
* Move the layout to individual pages and cleanup the index.tsx
* ~~Fix codeclimate issues~~
* ~~Move docs/CLIENT.md to client/README.md~~ (DONE)
* ~~Add user instructions in docs/CLIENT.md~~

**Comment by prasadtalasila** [comment]
@SyntaxXeror , just to confirm:
* Forward unknown routes to backend
* Move the layout to individual pages and cleanup the index.tsx

These two have been done, right?

**Comment by SyntaxXeror** [comment]
Yes they are done
