### ISSUE TITLE
Fix lib microservice

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#23]
The following changes are required to make the lib microservice work better:
1. There are warnings during `yarn install`, is it due to using not the latest packages?
2. lib microservice must generate `schema.gql` from codebase.

**Comment by prasadtalasila** [comment]
Adds docs/LIB-MS.md

**Comment by ravvnen** [comment]
After this, fix CodeClimate Issues

**Comment by ravvnen** [comment]
1. I have fixed the yarn install warnings, i removed @nestjs/axios, and updated rxjs aswell as express 
2. the schema does generate the schema.gql from the codebase already, using the graphqlmodule
3. I have a LIB-MS.md, but i would like to quickly draft it with you tomorrow

this is all in my dev branch - 

ref to the lib-ms.md .. https://github.com/ravvnen/DTaaS/blob/dev/docs/LIB-MS.md
ref to the graphql module .. line  13 - https://github.com/ravvnen/DTaaS/blob/dev/servers/lib/src/app.module.ts

**Comment by prasadtalasila** [comment]
Completed in PR #28
