### ISSUE TITLE
Failing unittest are not picked up by CI pipeline

### ISSUE THREAD

**Issue by Omarley7** [INTO-CPS-Association/DTaaS#42]
When a unit test fails `test.bash` is not exiting with any error code.

If the script is adapted to exit 1 if `jest .` it fixes the issue, but also introduces new issues:
1. Code coverage below the threshold will indistinguishably throw the same error code as if a test fails
2. When that happens, the coverage report will not be uploaded.

It can possibly be fixed by adding "Continue on error" to test step in pipeline and let the step fail if either coverage is below or a test fails.

@prasadtalasila what is the preferred behavior in this case?

**Comment by prasadtalasila** [comment]
We can insert the following bash option on after line-1
```bash
set -eux
```
Please see [this stackoverflow](https://stackoverflow.com/questions/2870992/automatic-exit-from-bash-shell-script-on-error?noredirect=1) question.

If it makes sense, you can add this behavior to other shell scripts.

**Comment by Omarley7** [comment]
The main issue is even if the tests pass, the coverage threshold in jest could fail and prevent the report to be uploaded. I've experimented with a similar setup the `set -eux`

```bash
jest .

JEST_EXIT_CODE=$?
if [ $JEST_EXIT_CODE -ne 0 ]; then
    printf "\n\n################ Jest tests failed ################"
    exit 1
fi
```
That evidently means we cannot get any code coverage uploaded below the threshold. The current relevant jest configuration:
```json
"coverageThreshold": {
    "global": {
      "branches": 20,
      "functions": 30,
      "lines": 50,
      "statements": 50
    }
  },
```

We could also remove the jest configuration and leave the threshold to be handled by CodeCov instead.

**Comment by Omarley7** [comment]
@prasadtalasila I would suggest keeping this open as a reminder to add the `-eux` options to the client test script, when test coverage is above the jest threshold.

**Comment by Omarley7** [comment]
Options has been set in test script
