### ISSUE TITLE
Construct routes for react website

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#47]
The react website requires route URLs for different pages. For example, there are the following URLs are required for workbench page. The usual convention is to hard code these URLs in the codebase. It's better to define these hard coded url partterns in env.js and let  envUtils.ts load them into the codebase.

The variable parts like username can be taken from the logged in username, but the rest have to come from env.js. ReactRouter is capable of this kind of URL construction. It might be better to combine the env.js URL fragments approach with the ReactRouters [Route component](https://reactrouter.com/en/main/route/route).

**Comment by prasadtalasila** [comment]
@KarstenMalle , the single sign on code stores the user information in the local storage. If a data structure for storing this user information is agreed upon, then the URL construction task can proceed further.

Is it possible discuss and agree  data structure in this thread of discussion?

PS: you don't have to provide code to return this information. If a structure is agreed upon, getter and setter functions can be written to access this data structure.

**Comment by KarstenMalle** [comment]
Currently I can just store it as a string, so for example if you want profile it would be "https://gitlab.com/@username".  I can also get just the username or just the name and store it as a string. I am not sure I understand what it is exactly that you want but hopefully this helps.

**Comment by prasadtalasila** [comment]
username as string is fine. As I understand, this string will be stored in localstorage of the browser. Others can work with this assumption. Take this username string and compose the required URLs for a logged in user.

**Comment by prasadtalasila** [comment]
The convention of username as string is sufficient to proceed further. We will push the react router work to future.
