### ISSUE TITLE
tests for http mode of libms fail

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#482]
PR #480 adds http mode to library microservice. The following yarn commands run on developer computer but fail on the github actions.

```sh
yarn test:http
yarn test:http-nocov
yarn test:http-github
```

These tests require libms to be running. The libms is launched and terminated on the developer computer using pm2 npm package. But this launch is failing in github actions.

**Comment by nichlaes** [comment]
@prasadtalasila  Does this qualify? https://github.com/INTO-CPS-Association/DTaaS/actions/runs/10467931474

**Comment by prasadtalasila** [comment]
@nichlaes 
Unfortunately not. The github actions uses `test:all` which ignores HTTP tests. The HTTP tests are in `test/cloudcmd`. The following commands of [package.json](https://github.com/INTO-CPS-Association/DTaaS/blob/676-libms-commander-error-on-windows/servers/lib/package.json) should work in github actions.

```
    "test:http": "yarn build && pm2 start -f --name libms-test dist/src/main.js -- -c .env -H ./config/http.json && jest test/cloudcmd --coverage --coverageThreshold=\"{}\" && pm2 delete libms-test",
    "test:http-github": "yarn build && yarn start:pm2 && jest test/cloudcmd --coverage --coverageThreshold=\"{}\" && pm2 delete libms",
```

These commands are commented out in [github actions](https://github.com/INTO-CPS-Association/DTaaS/blob/feature/distributed-demo/.github/workflows/lib-ms.yml) file. The actions must work even when the lines are uncommented.

**Comment by prasadtalasila** [comment]
PR #888 fixes this problem
