### ISSUE TITLE
iframe links for library and digital twin pages

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#49]
The [af17f91](https://github.com/INTO-CPS-Association/DTaaS/commit/af17f91957a9823a319da407e401b97fbdb27652) commit solves the issue of hardcoded links on the workbench page. Similar solution is required for library and digital twin pages.

This issue is a step up to issue #47.

**Comment by Omarley7** [comment]
Just to be clear, the Library and Digital Twins pages do not require username? It will just be:
- `{REACT_APP_URL_LIB}/functions | tools | models | data | digitaltwin`
- `{REACT_APP_URL_DT}/create | execute | analyse`

**Comment by prasadtalasila** [comment]
The configuration we are targeting is this:

```js
window.env = {
  REACT_APP_ENVIRONMENT: 'prod',
  REACT_APP_URL: 'https://ingenioer.au.dk/',
  REACT_APP_URL_DTLINK: '/lab',
  REACT_APP_URL_LIBLINK: '',
  REACT_APP_WORKBENCHLINK_TERMINAL: '/terminals/main',
  REACT_APP_WORKBENCHLINK_VNCDESKTOP: '/tools/vnc/?password=vncpassword',
  REACT_APP_WORKBENCHLINK_VSCODE: '/tools/vscode/',
  REACT_APP_WORKBENCHLINK_JUPYTERLAB: '/lab',
  REACT_APP_WORKBENCHLINK_JUPYTERNOTEBOOK: '',
};
```

The tabs on library and digital twins pages will not have their own URLs. So you don't need to construct URLs like  `{REACT_APP_URL_LIB}/[functions | tools | models | data | digitaltwin]`.

**Comment by prasadtalasila** [comment]
Looking from the user interaction side,
* when user goes to library page ---> the iframe shows `{REACT_APP_URL/${username}`
* when user goes to digital twins page ---> the iframe shows `{REACT_APP_URL/${username}/lab`

**Comment by Omarley7** [comment]
Ahh right, so the library "endpoints" (files, tools etc.) will be handled by the graphql request is suppose.

**Comment by prasadtalasila** [comment]
> Ahh right, so the library "endpoints" (files, tools etc.) will be handled by the graphql request is suppose.

yes

**Comment by prasadtalasila** [comment]
@Omarley7 is this done in a recent PR?

**Comment by Omarley7** [comment]
Yes, all routes now use the `envUtil` component to retrieve environment variables and incorporate it into the iframe URL.
