### ISSUE TITLE
VNC Error

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#583]
Sometimes (rarely) VNC view of user workspace shows an error.
![error_message_stuck](https://github.com/INTO-CPS-Association/DTaaS/assets/9206466/2a8f7022-462b-44b3-86f8-a5e3e967d3be)
The reason is not clear yet.

**Comment by mortenhaahr** [comment]
I do not have any console logs, as it was the VNC viewer program itself throwing the error. 

However, it has not occurred to me since that day.

**Comment by prasadtalasila** [comment]
This error could not be replicated.
