### ISSUE TITLE
Help and code icon on react website

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#584]
Add a help icon with hyperlink to online documentation. The link should come from `env.js`.

**Comment by LoiueFragosoUwUr** [comment]
Hi 
I would like to contribute to this issue

Is this link the right one to add to the env.js file ?

https://into-cps-association.github.io/DTaaS/development/index.html
![image](https://github.com/INTO-CPS-Association/DTaaS/assets/126754704/c3bfeb1c-5b8e-4c80-b123-698c9e77758c)

**Comment by LoiueFragosoUwUr** [comment]
I've been exploring your system and reading the documentation, could you just give me a hint about where should I add help button? 

please

**Comment by prasadtalasila** [comment]
@LoiueFragosoUwUr 
Thank you very much for your interest.

A bit more information about the issue:

![suggested image](https://github.com/INTO-CPS-Association/DTaaS/assets/9206466/cb73fa28-88af-4df7-9eae-8fe44c26d7fd)

The new icons are in the top right corner of the page. The links to be added are:
**github:** https://github.com/INTO-CPS-Association/DTaaS
**help:** https://into-cps-association.github.io/DTaaS


The relevant material icons are:

```
import HelpOutlineIcon from '@mui/icons-material/HelpOutline';
import GitHubIcon from '@mui/icons-material/GitHub';
```

**Comment by LoiueFragosoUwUr** [comment]
understood

**Comment by prasadtalasila** [comment]
completed in PR #731
