### ISSUE TITLE
E2E tests of lib microservice are brittle

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#59]
The end to end tests of lib microservice fail unpredictably. This might have to do with the fixed timeouts of [10,000 milliseconds](https://github.com/INTO-CPS-Association/DTaaS/blob/feature/distributed-demo/servers/lib/test/e2e/app.e2e.spec.ts) given in the test code. 

@ravvnen , can you please confirm if this is the case? Thanks.

**Comment by ravvnen** [comment]
Hello Prasad,
Yes they seemed to be abit brittle aswell earlier, hence i setup the timeout to give them more time to instantiate and close. Now when i test them on my linux i can run the tests continously without any errors.

Just ran yarn test -e, and yarn test -a 10 times in a row without any problems (all on my linux machine)

**Comment by prasadtalasila** [comment]
can you please check the github actions for [server](https://github.com/INTO-CPS-Association/DTaaS/actions/workflows/server.yml). The last few runs result in failures. You can try one more time and see if it helps.

**Comment by ravvnen** [comment]
But they shouldnt work via github actions since we are incorporating traefik?

**Comment by prasadtalasila** [comment]
In that case, please change [test -a](https://github.com/INTO-CPS-Association/DTaaS/blob/feature/distributed-demo/.github/workflows/server.yml#L38) to run only unit and integration tests.

**Comment by ravvnen** [comment]
Will do that

**Comment by prasadtalasila** [comment]
PR #65 takes care of this issue.
