### ISSUE TITLE
libms: commander error on Windows

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#676]
When libms is executed on Windows with

```shell
yarn start -H config/http.json
```

The following error pops up.

![image](https://github.com/INTO-CPS-Association/DTaaS/assets/9206466/b67f69a4-03a5-4054-8224-035c45da5169)

**Comment by prasadtalasila** [comment]
This problem is seen only on Windows. It could be the way **cloudcmd** handles paths. Requires further investigation.

**Comment by prasadtalasila** [comment]
Even `yarn test:http` fails on Windows

**Comment by nichlaes** [comment]
@prasadtalasila  It works on my windows machine now.

And I can run `yarn test:http` where the three tests passes. I don't get the error on the screenshot.

Problems I encountered.

**GraphQL-tag package not having a main.js**
I had to locally transpile the package. For some reason there was only a index.ts file. It did however work if I downloaded the package from npm registry. @prasadtalasila does it work for you if you `yarn clean` and the build and run the lib? (so I can know if it is only on my PC)

**Tests starting unlimited terminals if running in bash**
If I ran the tests from a bash shell it would keep creating terminals, when I ran the test command. So I had to restart the PC. **However it works when running from PowerShell**.

I fixed failing tests by making the tests independent of the files order. These changes are visible on the branch.

**Comment by prasadtalasila** [comment]
@nichlaes thanks for checking. Please see my responses below.

> And I can run `yarn test:http` where the three tests passes. I don't get the error on the screenshot.

The error screenshots are for `yarn start -H config/http.json`. Do you see them?


> Problems I encountered.
> 
> **GraphQL-tag package not having a main.js** I had to locally transpile the package. For some reason there was only a index.ts file. It did however work if I downloaded the package from npm registry. @prasadtalasila does it work for you if you `yarn clean` and the build and run the lib? (so I can know if it is only on my PC)
> 
I had to execute `.\node_modules\.bin\jest.cmd --clearCache` before `yarn test:http` could run successfully. 

> **Tests starting unlimited terminals if running in bash** If I ran the tests from a bash shell it would keep creating terminals, when I ran the test command. So I had to restart the PC. **However it works when running from PowerShell**.

The `yarn test:*` uses pm2 but the pm2 processes are not deleted after the tests. This is one of the problems.

The `yarn test:http`
does open multiple terminals on Windows but I am not sure why. It could be due to use of pm2 package but am still not sure. This could be the reason for system crash in bash. Can you please check why?

> I fixed failing tests by making the tests independent of the files order. These changes are visible on the branch.

Thanks. Please let me know the yarn command that got fixed.

**Comment by nichlaes** [comment]
@prasadtalasila I don't get the error, when running `yarn start -H config/http.json`

**Comment by nichlaes** [comment]
Update:

Relative paths works on both windows and linux.

Absolute paths doesn't work on Windows as it is now.

**Comment by nichlaes** [comment]
Windows absolute path doesn't work due to CloudCMD as of now. Therefore if run on Windows, paths needs to be relative.
