### ISSUE TITLE
Wrong READMEs in github packages

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#783]
GitHub Packages uses the README from the root of the repository for all packages in the repository. If you want to have a specific README for a package in a monorepo, you can use a workaround.

The workaround is to temporarily move to the package directory, copy the package-specific README to the root, publish the package, and then move the README back. Here's how you can do it:

```bash
# Move to the package directory
cd package

# Copy the package README to the root
cp README.md ../

# Publish the package
npm publish

# Restore the root README back
mv README.md packages/my-package/
```

This will ensure that the package-specific README is used when publishing the package to GitHub Packages. Remember to replace `packages/my-package` with the actual path to your package directory.

courtesy: Github co-pilot

**Comment by prasadtalasila** [comment]
This change is to be made in:

* github actions
* documentation

**Comment by prasadtalasila** [comment]
The pending problems to fix:

- Remove image links from README of `servers/lib`. Put all the images in the documentation.
- Correct READMEs for **dtaas-web** and **libms** docker images. A dedicated README is needed for each of the docker images. The filenames could be `docker/WEB.md` and `docker/LIBMS.md`. These files need to overwrite the top-level README in `docker.yml` workflow. It could be done on [line-39 of docker.yml](https://github.com/INTO-CPS-Association/DTaaS/blob/feature/distributed-demo/.github/workflows/docker.yml#L39). The name of the file must come as parameter to the yaml (similar in technique to `inputs.dockerfile`.

**Comment by prasadtalasila** [comment]
Also remember to remove the docker-specific information from READMEs of libms and client packages. The idea is to have separate READMEs for docker and npm packages. These READMEs should only contain information for the matching github package.

**Comment by aryanpingle** [comment]
Based on [this issue posted in `docker/build-push-action`](https://github.com/docker/build-push-action/issues/1093) and [this ongoing GitHub community thread](https://github.com/orgs/community/discussions/64967), it looks like the README file shown alongside a GitHub package **for a docker image** is that of the repository's, and cannot be set to a custom markdown file. This is not the case for GitHub packages deployed to NPM, which is why the `runner` and `libms` packages display the correct markdown file that we specify.

**Comment by aryanpingle** [comment]
The best practice we could follow is to add links in the DTaaS repository README, something like:

```
Introduction
 |--- Intro to the repository
 |--- Intro to the Docker Image
```

**Comment by prasadtalasila** [comment]
@aryanpingle Does the [path context](https://github.com/docker/build-push-action?tab=readme-ov-file#path-context) option help in anyway?

**Comment by aryanpingle** [comment]
From my testing, the git and path options help in setting the "context" of the docker container, i.e. letting you access different repositories and their workflows. This doesn't seem to solve the problem of the README file displayed on GitHub.

There is a config option called `org.opencontainers.image.source` which links a package to any repository of your choice. [GitHub currently uses predefined OCI annotations](https://docs.github.com/en/packages/learn-github-packages/connecting-a-repository-to-a-package#connecting-a-repository-to-a-container-image-using-the-command-line) to determine the README file displayed, so this might be the solution we're looking for. I'll try it out and post the results.
