### ISSUE TITLE
Force overwrite of docker images in github actions

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#854]
The github actions are supposed to publish only new versions of packages. This behavior is observed in npm packages but not docker images. In the case of docker images, all the commits to `client/` or `servers/lib` of `feature/distributed-demo` branch result in overwrite of existing images. This behavior is undesirable.

**Comment by nichlaes** [comment]
@prasadtalasila can you describe a bit more in depth, what the desired behavior is?

**Comment by prasadtalasila** [comment]
@nichlaes 
If the same version of docker image is already in the github container image registry, github must skip the docker image publication.

**Comment by prasadtalasila** [comment]
@nichlaes 
This [github action](https://github.com/INTO-CPS-Association/DTaaS/actions/runs/10973686551/job/30471363485) does not go to docker image publishing unless the npm publishing is successful. Does `lib-ms.yml` has the problem described in this issue?

**Comment by prasadtalasila** [comment]
> @nichlaes This [github action](https://github.com/INTO-CPS-Association/DTaaS/actions/runs/10973686551/job/30471363485) does not go to docker image publishing unless the npm publishing is successful. Does `lib-ms.yml` has the problem described in this issue?

The docker publication job in the [lib-ms](https://github.com/INTO-CPS-Association/DTaaS/actions/runs/10973686551/workflow#L155) depends on `npm-publish-package` job and this [workflow graph](https://github.com/INTO-CPS-Association/DTaaS/actions/runs/10978540311) shows the dependence clearly. Thus an npm package publish fails, docker image publish also fails. So it is not a problem for **lib-ms** package.

The problem is with the client. The docker publication job in the [client](https://github.com/INTO-CPS-Association/DTaaS/actions/runs/10956510555/workflow#L75) only depends on the successful running of the tests.
This [workflow graph](https://github.com/INTO-CPS-Association/DTaaS/actions/runs/10956510555) of client shows the problem clearly. If the tests are successful, docker image is either newly published or existing image rewritten.

The PR can be confirmed by checking the result on the client docker image.
