### ISSUE TITLE
Localhost install using docker desktop

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#944]
The existing installation commands are for CLI. For example, `docker compose ....` can only be executed from commandline. We are in need of screenshot-based installation instructions for docker desktop.

**Comment by aryanpingle** [comment]
Unfortunately, Docker Desktop does not provide a GUI-based alternative to `docker compose`.

Portainer is an alternative to Docker Desktop that seems to provide a GUI for everything apart from the initial command needed to run its container. Additionally, environment variables can be prompted to the user to modify.

**Comment by prasadtalasila** [comment]
completed via PR #1037 and #1039
