### ISSUE TITLE
Update admin documentation

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#96]
1. Make sure that all the code in `deploy/` and `script/` have been correctly ported from `release-v0.2` branch to `feature/distributed-demo`. (cross-check PR #94) **- (Done)**

1. The "Admin" tab is really "Installation", though there may be administrative (post-install) tasks there too. But it leaps into the detail of the installation without explaining that there are multiple stages and different bits of software that need to be installed in stages. This level of description may make sense for members of the development team, but to someone unfamiliar it is very difficult to follow/understand. **- (Done)**
 
1. There needs to be an overview of the installation in terms of "we're going to do this, then we're going to do that" so that an unfamiliar user can follow it more easily. Ideally, you need to be able to take a smart (but unfamiliar) person and put them in a room with this website, and have them follow your instructions to install the product. As it stands, I think they would be very confused very quickly.(cross-check PR #215) **- (Done)**

1. The instructions and install.sh need to be updated for basepath. All the ml-workspace containers need to have basepath as well. See issue #88 for more information

1. Add installation instructions for Gitlab OAuth integration. **- (Done)**

1. Add representative network diagrams on all the installation pages (the docs/developer/system/DTaaS.drawio) (cross-check PR #215) **- (Done)**

1. Admin --> Installation --> Cookbook page
    *  create a `docs/admin/guides` to add notes on modifications to the standard deployment scenarios. Currently known scenarios:
     * add more users **- (Done)**
     * add other services 
     * link services to local ports using SSH port mapping
     * restrict user to read only permissions to common/ directory
     * hosting the site without SSL certificates
     * add self-signed (`ssl/`) / LetsEncrypt certificates
     * add or remove TLS certificates to gateway

1. Update servers/config/gateway/README.md to include auth in the volume mapping of docker container. **- (Done)**

1. Update the servers/config/gateway/README.md for traefik-gateway launch command to use auth. **- (Done)**
    ```bash
    docker run -d \
     --name "traefik-gateway" \
     --network=host -v "$PWD/traefik.yml:/etc/traefik/traefik.yml" \
     -v "$PWD/auth:/etc/traefik/auth" \
     -v "$PWD/dynamic:/etc/traefik/dynamic" \
     -v /var/run/docker.sock:/var/run/docker.sock \
     traefik:v2.5
    ```
1. Document basepath installations and possibility of multiple installations. See [issue #88](https://github.com/INTO-CPS-Association/DTaaS/issues/88)
1. One Mermaid diagram showing the installation of different software components (cross-check PR #215) **- (Done)**

**Comment by prasadtalasila** [comment]
The [Ubuntu desktop install](https://ubuntu.com/tutorials/install-ubuntu-desktop#1-overview) is a good inspiration for structuring the install documentation.

**Comment by prasadtalasila** [comment]
The users are need to run it from top-level. Please see this [README](https://github.com/INTO-CPS-Association/DTaaS/blob/feature/distributed-demo/deploy/README.md#perform-the-installation).

```bash
source deploy/install.sh
```

The installation steps require strict sequence of steps. We will improve upon them to automate most of these steps in near future.

**Comment by nichlaes** [comment]
> 9. Update the servers/config/gateway/README.md for traefik-gateway launch command to use auth.

Updated on [branch 96-update-admin-documentation](https://github.com/INTO-CPS-Association/DTaaS/tree/96-update-admin-documentation)

**Comment by nichlaes** [comment]
### **Comments**:

#### Admin section:

1) **Add a general purpose section**
A section which shortly describes the role as an admin for the system and what the goal is. What am I installing? It relates to task/comment (2.), but maybe an even more general intro/overview of the admin role would make sense.   

### Questions: 

Should I run test the 'admin doc install guide' on the DTaaS integration server or do you have another linux server available I can test on? My own PC is running windows machine.

>4. The instructions and install.sh need to be updated for basepath. All the ml-workspace containers need to have basepath as well. See issue [Update install instructions for basepath #88](https://github.com/INTO-CPS-Association/DTaaS/issues/88) for more information

I know me talked about this one, but I'm not sure what and where to update. Is this already done? 

>6. Add representative network diagrams on all the installation pages (the docs/developer/system/DTaaS.drawio)

Are the network diagram already made? If yes which one is it in the draw.io file, the first one?

>7. Admin --> Installation --> Cookbook page
>    
    - create a `docs/admin/guides` to add notes on modifications to the standard deployment scenarios. Currently known scenarios:
    - add more users
    - add other services
    - link services to local ports using SSH port mapping
    - admin user with read-write permissions to common/ directory
    - add self-signed (`ssl/`) / LetsEncrypt certificates
    - add or remove TLS certificates to gateway
    - hosting the site without SSL certificates

Is this already written somewhere or do I need to write this? If so I think this would take me some time, because I have a knowledge gap, and each scenario would need to be specified further in order for me to understand.

>10. Document basepath installations and possibility of multiple installations. See [issue #88](https://github.com/INTO-CPS-Association/DTaaS/issues/88)

Same question as number 4.

>11. One Mermaid diagram showing the installation of different software components

Not sure how to do this one and what the requirements are. Is it to take one of the draw.io diagrams and convert to Mermaid diagram?

**Comment by prasadtalasila** [comment]
> @prasadtalasila
> ### **Comments**:
> #### Admin section:
> 
>     1. **Add a general purpose section**
>        A section which shortly describes the role as an admin for the system and what the goal is. What am I installing? It relates to task/comment (2.), but maybe an even more general intro/overview of the admin role would make sense.
> 
The [Ubuntu install procedure](https://ubuntu.com/tutorials/install-ubuntu-desktop#1-overview) gives a template for what we can write about the installation steps. Let us follow that for now.

> 
> ### Questions:
> 
> Should I run test the 'admin doc install guide' on the DTaaS integration server or do you have another linux server available I can test on? My own PC is running windows machine.
> 
The integration server

> > 4. The instructions and install.sh need to be updated for basepath. All the ml-workspace containers need to have basepath as well. See issue [Update install instructions for basepath #88](https://github.com/INTO-CPS-Association/DTaaS/issues/88) for more information
> 
> I know me talked about this one, but I'm not sure what and where to update. Is this already done?
Not done yet. The places where the changes may be required are:

* [gateway config in deployment](https://github.com/INTO-CPS-Association/DTaaS/blob/feature/distributed-demo/deploy/config/gateway/fileConfig.yml)
* [install](https://github.com/INTO-CPS-Association/DTaaS/blob/feature/distributed-demo/deploy/install.sh) script
* [single script install](https://github.com/INTO-CPS-Association/DTaaS/blob/feature/distributed-demo/deploy/single-script-install.sh) script
* New documentation file for [basepath](https://github.com/INTO-CPS-Association/DTaaS/tree/feature/distributed-demo/docs/admin/servers)
* Minor cleanup of client config in [deploy](https://github.com/INTO-CPS-Association/DTaaS/blob/feature/distributed-demo/deploy/config/client/env.js) and [client/config](https://github.com/INTO-CPS-Association/DTaaS/tree/feature/distributed-demo/client/config)

> > 6. Add representative network diagrams on all the installation pages (the docs/developer/system/DTaaS.drawio)
> 
> Are the network diagram already made? If yes which one is it in the draw.io file, the first one?
No

> 
> > 7. Admin --> Installation --> Cookbook page
> 
> ```
> - create a `docs/admin/guides` to add notes on modifications to the standard deployment scenarios. Currently known scenarios:
> - add more users
> - add other services
> - link services to local ports using SSH port mapping
> - admin user with read-write permissions to common/ directory
> - add self-signed (`ssl/`) / LetsEncrypt certificates
> - add or remove TLS certificates to gateway
> - hosting the site without SSL certificates
> ```
> 
> Is this already written somewhere or do I need to write this? If so I think this would take me some time, because I have a knowledge gap, and each scenario would need to be specified further in order for me to understand.
> 
I have the steps written in a markdown file. We can discuss a way to get this done easily

> > 10. Document basepath installations and possibility of multiple installations. See [issue #88](https://github.com/INTO-CPS-Association/DTaaS/issues/88)
> 
> Same question as number 4.
> 

> > 11. One Mermaid diagram showing the installation of different software components
> 
> Not sure how to do this one and what the requirements are. Is it to take one of the draw.io diagrams and convert to Mermaid diagram?
The mermaid is a JS package to draw UML diagrams. It is already integrated into the documentation pipeline. Please see this example diagram for [library microservice](https://into-cps-association.github.io/DTaaS/development/developer/servers/lib/lib-ms.html#sequence-diagram). You will probably be making a deployment diagram for this. If mermaid is not capable of doing this, we will use the drawio.

Hope the explanation helps. We will meet soon anyway and so we can discuss more soon. Thanks.

**Comment by nichlaes** [comment]
@prasadtalasila 
I have started restructuring some of the documentation.

I have noted some reflections while trying the trial installation.

- When the installation is complete (e.g trial), how do I know that it is complete? Should I just access the site, or should I also try out a DigitalTwin/algorithm.

- When accessing the website, I am prompted by a username and password, this is not mentioned in the installation guide?

- Does the OAuth Provider have to be GitLab or could it be any OAuthProvider?

**Comment by prasadtalasila** [comment]
@nichlaes am not sure if you received answers to these questions. In case you did not receive them, please see below.

> @prasadtalasila I have started restructuring some of the documentation.
> 
> I have noted some reflections while trying the trial installation.
> 
>     * When the installation is complete (e.g trial), how do I know that it is complete? Should I just access the site, or should I also try out a DigitalTwin/algorithm.
> 
For now, just access the website and check all the steps outlined in `docs/user/website/index.md`.

>     * When accessing the website, I am prompted by a username and password, this is not mentioned in the installation guide?
> 
This is the password check made by Traefik gateway. It should be made obvious in the installation documentation.

Your idea of post-install checklist is a good one. Can you please add a page to the admin documentation section describing the checklist steps and the expected results?

>     * Does the OAuth Provider have to be GitLab or could it be any OAuthProvider?

It can be any OAuth provider. But the gitlab is also integrated into other components of DTaaS software. Thus having another OAuth provider will be extra work for user. This question and the explanation is a good candidate for **admin cookbook** section.

**Comment by prasadtalasila** [comment]
# Adding more users

```bash
cd DTaaS/files
cp -R user2 <username>
cd ..
docker run -d \
 -p <port>:8080 \
  --name "ml-workspace-<username>" \
  -v "${TOP_DIR}/files/mirgita:/workspace" \
  -v "${TOP_DIR}/files/<username>:/workspace/common" \
  --env AUTHENTICATE_VIA_JUPYTER="" \
  --env WORKSPACE_BASE_URL="<username>" \
  --shm-size 512m \
  --restart always \
  mltooling/ml-workspace:0.13.2

cd servers/config/gateway
htpassword auth <username>

vi dynamic/fileConfig.yml

http:
  routers:
    ....
    <username>:
      entryPoints:
        - http
      rule: 'Host(`foo.com`) && PathPrefix(`/<username>`)'
      middlewares:
        - basic-auth
      service: <username>

  services:
    ...
    <username>:
      loadBalancer:
        servers:
          - url: 'http://localhost:<port>'
```

**Comment by prasadtalasila** [comment]
# Add new services

Provide instructions for installing MongoDB

**Comment by nichlaes** [comment]
Hi @prasadtalasila 

When I try to install the trial version, I get the following error: 

`cp: cannot stat '/home/vagrant/DTaaS/deploy/config/client/env.js': No such file or directory`

Do you have an idea why this happens?

I'll investigate further.

**Comment by prasadtalasila** [comment]
PR #300 completes most of this work.
