### ISSUE TITLE
[BUG] Dependabot error for libms

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/DTaaS#982]
### Describe the bug

The dependabot is throwing up an error for builds of libms. Please see this [build log](https://github.com/INTO-CPS-Association/DTaaS/actions/runs/11323750980/job/31487069050)

### To Reproduce

1. Rerun github actions workflow of libms [lib-ms.yml](https://github.com/INTO-CPS-Association/DTaaS/actions/workflows/lib-ms.yml)
1. See error on the workflow logs page

### Expected behavior

Dependabot shows no errors.

**Comment by prasadtalasila** [comment]
@nichlaes does this error still exist?

**Comment by nichlaes** [comment]
I couldn't reproduce it.
