### ISSUE TITLE
[BUG]  Incorrect label with docker

### ISSUE THREAD

**Issue by gitting-around** [INTO-CPS-Association/DTaaS#985]
### Describe the bug

I am attempting to run DTaaS on localhost, and there is a failure at docker compose up.

### Steps:

I have already created a local user.
Initially I did a git pull.

Then, I go to:
`$ cd deploy/docker`

I run the following in the terminal:
`$ docker compose -f compose.local.yml --env-file .env.local up -d`

I get the following error:
`network dtaas-frontend was found but has incorrect label com.docker.compose.network set to "dtaas-frontend"`

Trying multiple times, can end up with a slightly different error:
`network dtaas-users was found but has incorrect label com.docker.compose.network set to "dtaas-users"`

### Application Environment

Please provide the following information:

- OS: MacOS Sequoia 15.0.1 (24A348)
- Browser Firefox
- DTaaS Release branch feature/distributed-demo, commit bfa34e072e4fbd842c4c08dc0926966afc0e9597.

**Comment by prasadtalasila** [comment]
@gitting-around please post the output of `docker ps -a`, `docker -v` and `docker-compose -v` commands. Thanks.

**Comment by gitting-around** [comment]
`docker ps -a`:
`CONTAINER ID   IMAGE        COMMAND       CREATED        STATUS                     PORTS   NAMES                                                                                                                           
ac32fa9beea6   influxdb     "/entrypoint.sh infl…"   5 weeks ago    Exited (255) 3 weeks ago   0.0.0.0:8086->8086/tcp, 0.0.0.0:8088->8088/tcp                                                                                        influxdb-server
d801d5e10679   rabbitmq    "docker-entrypoint.s…"   5 weeks ago    Exited (255) 3 weeks ago   4369/tcp, 0.0.0.0:1883->1883/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 15691-15692/tcp, 0.0.0.0:15672->15672/tcp, 25672/tcp   rabbitmq-server
9dfc557d18b1   mltooling/ml-workspace-minimal:0.13.2   "/tini -g -- python …"   4 months ago   Up 3 hours                 8080/tcp                                                                                                                              docker_user1_1
c6853d14c91c   traefik:v2.10   "/entrypoint.sh --ap…"   4 months ago   Up 3 hours                 0.0.0.0:80->80/tcp                                                                                                                    docker_traefik_1`

`docker -v`: Docker version 26.1.4, build 5650f9b

`docker-compose -v`: complains about docker-compose not found.
I tried `docker compose version`: Docker Compose version v2.27.1-desktop.1

**Comment by prasadtalasila** [comment]
This is not a bug in DTaaS. It comes because of a problem with docker (best guess right now). A fix is to run

```sh
docker network rm dtaas-frontend
docker network rm dtaas-users
```
